[package]
name = "starlark-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
anyhow = "1.0.69"
libfuzzer-sys = "0.4"

[dependencies.starlark]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "starlark"
path = "fuzz_targets/starlark.rs"
test = false
doc = false
