/*
 * Copyright 2026 The Starlark in Rust Authors.
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! Macro for registering `AsTypeStaticRegistered` trait impls for pagable serde.
//!
//! This macro exists because the `#[starlark_module]` proc macro cannot use
//! `#[cfg(feature = "pagable")]` directly in its output — cfg attributes in
//! proc macro output are evaluated in the **consumer crate's** context, not
//! starlark's. Since the `pagable` feature belongs to the starlark crate,
//! an inline `#[cfg(feature = "pagable")]` in generated code would always
//! evaluate to false in consumer crates.
//!
//! By delegating to this `#[macro_export]` macro, the `#[cfg]` on the macro
//! **definition** is evaluated during starlark's compilation, ensuring the
//! correct variant is selected based on starlark's feature flags.

/// When pagable is enabled, generate the `AsTypeStaticRegistered` trait impl.
#[cfg(feature = "pagable")]
#[macro_export]
#[doc(hidden)]
macro_rules! __register_starlark_value_as_type {
    (impl_trait = $inner_ty:ty) => {
        // SAFETY: This impl is generated by #[starlark_module] alongside the static
        // registration, ensuring the type is properly registered for pagable serialization.
        unsafe impl $crate::values::starlark_value_as_type::AsTypeStaticRegistered for $inner_ty {}
    };
}

/// When pagable is disabled, expand to nothing (blanket impl covers all types).
#[cfg(not(feature = "pagable"))]
#[macro_export]
#[doc(hidden)]
macro_rules! __register_starlark_value_as_type {
    ($($tt:tt)*) => {};
}
