name: ci
on:
  push:
  pull_request:
  schedule:
  - cron: '0 12 * * 1' # 12pm Monday
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        toolchain: [stable]
        include:
          - toolchain: nightly
            os: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.toolchain }}
        components: clippy, rustfmt
    # We use rustfmt 2.0 for formatting, which differs from the released
    # version installed by Cargo
    # - run: cargo fmt -- --check
    - run: cargo clippy
    - run: cargo build
    - run: cargo test
    - run: cargo bench
    - uses: EmbarkStudios/cargo-deny-action@v1
      if: matrix.os == 'ubuntu-latest' # Only works on Linux
      with:
        command: check bans sources
